version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

commands:
  install_toolset:
    description: "Install needed extra tools"
    steps:
      - run:
          name: Intall tools
          command: |
            curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/
            curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/
    
  wait_for_dpkg:
    description: "Wait for packaging operations to finish"
    steps:
      - run:
          name: Wait for packaging operations to finish
          command: |
            sleep 10
            while systemctl status apt-daily >/dev/null || systemctl status apt-daily-upgrade >/dev/null || sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock; do
              echo "waiting 30s for dpkg locks..."
              sleep 30
            done
jobs:
  start_minnaker:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - install_toolset
      - wait_for_dpkg
      - run:
          name: Install Spinnaker
          command: |
            .circleci/libs/install-and-run-spinnaker.sh
      - run:
          name: Check if everything is still working
          command: |
            kind get clusters
            kubectl get pods -n spinnaker

workflows:
  test:
    jobs:
      - start_minnaker

