version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

commands:
  wait_for_dpkg:
    description: "Wait for packaging operations to finish"
    steps:
    - run:
        name: "Wait for packaging operations to finish"
        command: |
          sleep 10
          while systemctl status apt-daily >/dev/null || systemctl status apt-daily-upgrade >/dev/null || sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock; do
          echo "waiting 30s for dpkg locks..."
          sleep 30
          done
jobs:
  start_minnaker:
    machine:
      image: ubuntu-1804
    steps:
      - run:
          command: uname -a

workflows:
  test:
    jobs:
      - start_minnaker

